<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HUNTER" ignored="5" name="Default test" tests="1" failures="1" timestamp="04 Jul 2020 07:02:55 GMT" time="116.227" errors="0">
  <testcase name="removePimLogo" time="96.35" classname="unbxdTests.testNg.ui.pim.OrganisationProfile_Tests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at unbxdTests.testNg.ui.pim.OrganisationProfile_Tests.removePimLogo(OrganisationProfile_Tests.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- removePimLogo -->
  <testcase name="verifyOrganisationProfilePage" time="0.0" classname="unbxdTests.testNg.ui.pim.OrganisationProfile_Tests">
    <ignored/>
  </testcase> <!-- verifyOrganisationProfilePage -->
  <testcase name="uploadOrgImage" time="0.0" classname="unbxdTests.testNg.ui.pim.OrganisationProfile_Tests">
    <ignored/>
  </testcase> <!-- uploadOrgImage -->
  <testcase name="verifyImageUrl" time="0.0" classname="unbxdTests.testNg.ui.pim.OrganisationProfile_Tests">
    <ignored/>
  </testcase> <!-- verifyImageUrl -->
  <testcase name="addPimLogo" time="0.0" classname="unbxdTests.testNg.ui.pim.OrganisationProfile_Tests">
    <ignored/>
  </testcase> <!-- addPimLogo -->
  <testcase name="verifyOrgName" time="0.0" classname="unbxdTests.testNg.ui.pim.OrganisationProfile_Tests">
    <ignored/>
  </testcase> <!-- verifyOrgName -->
</testsuite> <!-- Default test -->
