<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="5" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="116227" started-at="2020-07-04T07:00:58Z" finished-at="2020-07-04T07:02:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="116227" started-at="2020-07-04T07:00:58Z" finished-at="2020-07-04T07:02:55Z">
      <class name="unbxdTests.testNg.ui.pim.OrganisationProfile_Tests">
        <test-method status="PASS" signature="init()[pri:0, instance:unbxdTests.testNg.ui.pim.OrganisationProfile_Tests@769f71a9]" name="init" is-config="true" duration-ms="11992" started-at="2020-07-04T12:30:58Z" finished-at="2020-07-04T12:31:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="removePimLogo()[pri:5, instance:unbxdTests.testNg.ui.pim.OrganisationProfile_Tests@769f71a9]" name="removePimLogo" duration-ms="96350" started-at="2020-07-04T12:31:10Z" finished-at="2020-07-04T12:32:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at unbxdTests.testNg.ui.pim.OrganisationProfile_Tests.removePimLogo(OrganisationProfile_Tests.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removePimLogo -->
        <test-method status="PASS" signature="logout()[pri:0, instance:unbxdTests.testNg.ui.pim.OrganisationProfile_Tests@769f71a9]" name="logout" is-config="true" duration-ms="7860" started-at="2020-07-04T12:32:47Z" finished-at="2020-07-04T12:32:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- unbxdTests.testNg.ui.pim.OrganisationProfile_Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
